services: mongodb
language: node_js
node_js:
- '5.11'
addons:
  code_climate:
    repo_token: 4e097cff96a54c4eac450b7aff1fa6fa1983f9d17f9be63f2e7119267767346a
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: heroku
  on: master
  app: safe-springs-47497
  api_key:
    secure: g+g9s56a+B++vvEq4VT6qkidi6tssdPGaUYU0jYpM7V1HxqCdsaoayEO+4PhNFqSouiNlk1jquzViX7Rxc1DoAK+IPv+uF2RDwfqefH7SApXcZy3SiteKze9ovOq93SZn8Y+MO95Fx/qBoqG7ozbOyjG2pnfuHWcCbI2KZ7UILXadzBRbov2Mla68uTIH5RY01xJeh3wZ02uDcdv4iN3BOsVUNJNF7i4RQD6rrXC4Sf7kY15sMjjk8mmYv2k7WkqwkJto/RGRFSSsM3hvT4r/dmRYnECQcLJ3+0ANiQeM6kbJS7n8t16JF8Ckz8YLdRfdOtoC+n9w+t6dMxYd1+a8/2u0leqgtC+S6mW+LjRqAH8Zs3F8nK43lgwbMAY7NkZDAGmGl9s4kDXBlV/NnYXw8Y5T5OXYqAumFmufKjOWxE2to/GGMpNV/jH7ovexrXDhIFYcsvHytdydQHTEsuxslyxAiCri1zq4uJJBIOEQIkQlirhhY9Ps5aEj/0YIuw22rqiI5VN8Ev4L/fZeqwLNuRvUjOri0bp6+08EHbOCKIYWxdbv6fMg7CNlrySLZLC3W2fn/CFAZRW63Q9b2up0NXMEg3le0yaBZ/aA2Zw1jsikExlBLRBS69b+i8Sfderfo0yAwnkv94OVqpuw7zDKGaO7QCopZTb5hv9XoYfR2Y=